name: CI/CD for Java Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configuración de Node.js (requisito para Vercel CLI)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Usar una versión LTS

    # 3. Configuración de JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # 4. Cacheo de dependencias Maven
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 5. Construcción y empaquetado con Maven
    - name: Build and package with Maven
      run: mvn clean package

    # 6. Instalación de Vercel CLI
    - name: Install Vercel CLI
      run: npm install -g vercel

    # 7. Despliegue a Vercel (condicional si la construcción fue exitosa)
    - name: Deploy to Vercel
      if: ${{ success() }}
      run: vercel --prod --yes
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    # 8. Verificación del despliegue
    - name: Verify deployment
      if: ${{ success() }}
      run: vercel inspect --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
